In [2]:
#importar pandas
import pandas as pd

In [3]:
#visualizar base de treino
treino = pd.read_csv('../data/raw/train.csv')
treino.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [4]:
#importar ProfileReport de ydata_profiling
from ydata_profiling import ProfileReport

In [5]:
#gerar visualização
profile = ProfileReport(treino, title="titanic_treino")

In [6]:
#criar relatório
profile.to_file("titanic_treino.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:00<00:00, 106861.25it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
#verificar as informações da base 
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
#vericar os tipos de dados
treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [9]:
#valores nulos
treino.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [10]:
#visualizar base de teste
teste = pd.read_csv('../data/raw/test.csv')
treino.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [12]:
#valores nulos em teste
teste.isnull().sum().sort_values(ascending=False).head(5)

Cabin     327
Age        86
Fare        1
Name        0
Pclass      0
dtype: int64

A base teste possui colunas com valores vazios que não estão na base de treino, nesse caso precisariamos tratar essas colunas apenas na base de teste

Tratamentos iniciais dos dados

In [13]:
# verificar novamente valores vazios para a base de treino
treino.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [14]:
# verificar shape da base
treino.shape

(891, 12)

In [15]:
#verificar novamente a base
treino.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
# verificar a cardinalidade dos dados
treino.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

Colunas com alta cardinalidade não vão ajudar o modelo pois podem torna-ló menos generalizadável, nesse caso, a melhor alternativa é remover essas colunas do conjunto de dados.

In [17]:
#eliminando para a base de treino
treino = treino.drop(['Name','Ticket','Cabin'], axis=1)

In [18]:
#eliminando para a base de teste
teste = teste.drop(['Name','Ticket','Cabin'], axis=1)

Agora a coluna Age será tratada, pois possui valores vazios tanto em de treino quanto em teste. Como essa coluna apresenta a idade dos passageiros, utilizarei a média das idades para substituir os valores vazios.

In [19]:
# verificar a média das idades da base de treino
treino.Age.mean()

np.float64(29.69911764705882)

In [20]:
#selecionar as colunas com idade vazia para substituir por essa média na base de treino
treino.loc[treino.Age.isnull(), 'Age'] = treino.Age.mean()

In [21]:
# #selecionar as colunas com idade vazia para substituir por essa média na base de teste
teste.loc[teste.Age.isnull(), 'Age'] = teste.Age.mean()

In [22]:
#verificar os valores na coluna Embarked
treino.Embarked .value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [23]:
#moda da coluna
treino.Embarked.mode()[0]

'S'

In [24]:
#substituir valores vazios
treino.loc[treino.Embarked.isnull(), 'Embarked'] = treino.Embarked.mode()[0]

In [25]:
#varificar a média da coluna Fare para a base de teste
teste.loc[teste.Fare.isnull(),'Fare']= teste.Fare.mean()

Verificar novamente valores vazios

In [26]:
# para a base de treino
treino.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [27]:
# para a base de teste
teste.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
dtype: int64

Colunas que não são de texto

In [30]:
# verificar colunas de texto na base de treino
col_treino_nr = treino.columns[treino.dtypes != 'object']
col_treino_nr

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [32]:
# selecionando apenas valores númericos da base de treino
treino_nr = treino.loc[:, col_treino_nr]

In [34]:
# verificar colunas de texto na base de teste
col_teste_nr = teste.columns[teste.dtypes != 'object']
col_teste_nr

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [35]:
# selecionando apenas valores númericos da base de teste
teste_nr = teste.loc[:, col_teste_nr]